# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
        verbose: true
      - id: end-of-file-fixer
        exclude: locales/
      - id: check-yaml

  # - repo: https://github.com/python-poetry/poetry-plugin-export
  #   rev: '1.6.0'
  #   hooks:
  #     - id: poetry-export
  #       args: ["-f", "requirements.txt", "--output", "requirements.txt", "--without-hashes"]
  #       verbose: true
