name: "Feature request 🚀"
description: Suggest an idea for this project
labels: [feature, Needs-Triage]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure to [search for existing issues](https://github.com/mgylabs/mkbot/issues) before filing a new one!

  - type: textarea
    id: feature
    attributes:
      label: Description of the new feature/enhancement
      placeholder: |
        A clear and concise description of what the problem is that the new feature would solve.
        Describe why and how a user would use this new functionality (if applicable).
    validations:
      required: true

  - type: textarea
    id: technical
    attributes:
      label: Proposed technical implementation details (optional)
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: false
