name: Static Analysis

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

env:
  DEFAULT_PYTHON: "3.10"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    name: lint
    runs-on: windows-2019
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "poetry"
      - uses: webfactory/ssh-agent@v0.7.0
        name: Install SSH key
        id: install-ssh
        continue-on-error: true
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Install dependencies
        env:
          SSH_OUTCOME: ${{ steps.install-ssh.outcome }}
        run: |
          if ($Env:SSH_OUTCOME -eq "success") {
            poetry install --no-root -E release
          } else {
            poetry install --no-root
          }
      - name: pylint
        if: ${{ always() }}
        run: |
          poetry run pylint src/bot src/msu src/lib
      - name: black
        if: ${{ always() }}
        run: |
          poetry run black --check .
      - name: flake8
        if: ${{ always() }}
        run: |
          poetry run flake8 --count --show-source --statistics

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: pre-commit
        run: |
          pre-commit run --all-files
