name: Static Analysis

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  lint:
    name: lint
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Cancel Previous Runs
        if: github.ref != 'refs/heads/main'
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: webfactory/ssh-agent@v0.5.1
        name: Install SSH key
        id: install-ssh
        continue-on-error: true
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Install dependencies 1
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt ; if ($LASTEXITCODE) { exit $LASTEXITCODE }
          if ($Env:DEPLOY_TOKEN) { pip install -U mulgyeol-oauthlib --index-url https://${Env:DEPLOY_USER}:${Env:DEPLOY_TOKEN}@gitlab.com/api/v4/projects/20530638/packages/pypi/simple --extra-index-url https://pypi.org/simple }
        shell: pwsh
      - name: Install dependencies 2
        if: steps.install-ssh.outcome == 'success'
        run: |
          pip install git+ssh://git@github.com/MycroftKang/application-insights-python.git
        shell: pwsh
      - name: pylint
        if: ${{ always() }}
        run: |
          pylint src tests
      - name: black
        if: ${{ always() }}
        run: |
          black --check .
      - name: flake8
        if: ${{ always() }}
        run: |
          flake8 --count --show-source --statistics

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: github.ref != 'refs/heads/main'
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: pre-commit
        run: |
          pre-commit run --all-files
