name: Static Analysis

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  lint:
    name: lint
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
      - name: Cancel Previous Runs
        if: github.ref != 'refs/heads/main'
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: webfactory/ssh-agent@v0.5.1
        name: Install SSH key
        id: install-ssh
        continue-on-error: true
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
        shell: pwsh
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install dependencies 1
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt ; if ($LASTEXITCODE) { exit $LASTEXITCODE }
        shell: pwsh
      - name: Install dependencies 2
        if: steps.install-ssh.outcome == 'success'
        run: |
          pip install --no-cache-dir git+ssh://git@github.com/MycroftKang/application-insights-python.git
        shell: pwsh
      - name: pylint
        if: ${{ always() }}
        run: |
          pylint src/bot src/msu src/lib
      - name: black
        if: ${{ always() }}
        run: |
          black --check .
      - name: flake8
        if: ${{ always() }}
        run: |
          flake8 --count --show-source --statistics

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: github.ref != 'refs/heads/main'
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: pre-commit
        run: |
          pre-commit run --all-files
