name: Build and Test

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
# on: [push, pull_request]

env:
  DEFAULT_PYTHON: "3.10"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: build and test
    runs-on: windows-2019
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "poetry"
      - uses: webfactory/ssh-agent@v0.7.0
        name: Install SSH key
        id: install-ssh
        continue-on-error: true
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Check lock file
        run: poetry lock --check
      - name: Install dependencies
        env:
          SSH_OUTCOME: ${{ steps.install-ssh.outcome }}
        run: |
          if ($Env:SSH_OUTCOME -eq "success") {
            poetry install --no-root -E release
          } else {
            poetry install --no-root
          }
      - name: Unit Test
        run: |
          poetry run pytest
      - name: Version
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run python package/vc.py -gb ; if ($LASTEXITCODE) { exit $LASTEXITCODE }
          echo "mkbot_version=$(cat version.txt)" >> $env:GITHUB_ENV
          if ($Env:API_KEY) { echo $Env:API_KEY > src\lib\mgylabs\constants\APIKey.py }
      - name: Build MK Bot
        run: |
          poetry run scripts\build.bat --canary
      - name: Test with dry run
        run: |
          mkdir $Env:USERPROFILE\.mkbot-canary > $null
          mkdir "$Env:LOCALAPPDATA\Mulgyeol\Mulgyeol MK Bot Canary" > $null
          cp -Path package\data -Destination "$Env:LOCALAPPDATA\Mulgyeol\Mulgyeol MK Bot Canary" -Recurse
          cp -Path extensions -Destination $Env:USERPROFILE\.mkbot-canary -Recurse
          cd .\build\bin
          .\MKBotCore.exe --dry-run
      - name: Packaging
        run: |
          & "${Env:programfiles(x86)}\Inno Setup 6\iscc.exe" "/DNameLong=Mulgyeol MK Bot Canary" "/DNameShort=MK Bot Canary" "/DVersion=${Env:mkbot_version}" "/DAppExeName=MKBot-Canary.exe" "/DAppMutex=MKBotCanary" "/DExtDirName=.mkbot-canary" "/DDName=mkbot-can" "package\MKBot.iss"
