name: Build and Test

on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*
# on: [push, pull_request]

jobs:
  build:
    name: build and test
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Cancel Previous Runs
        if: github.ref != 'refs/heads/master'
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt ; if ($LASTEXITCODE) { exit $LASTEXITCODE }
          if (Test-Path Env:DEPLOY_TOKEN) { pip install -U mulgyeol-oauthlib --index-url https://${Env:DEPLOY_USER}:${Env:DEPLOY_TOKEN}@gitlab.com/api/v4/projects/20530638/packages/pypi/simple --extra-index-url https://pypi.org/simple }
        shell: pwsh
      - name: Unit Test
        run: |
          python -m unittest discover -v -s tests -p test_*.py
      - name: Version
        run: |
          python package/vc.py -gb
          echo "mkbot_version=$(cat version.txt)" >> $env:GITHUB_ENV
        shell: pwsh
      - name: Build MK Bot
        run: |
          call scripts\build.bat
      - name: Test with dry run
        run: |
          mkdir $Env:USERPROFILE\.mkbot
          mkdir "$Env:LOCALAPPDATA\Mulgyeol\Mulgyeol MK Bot"
          cp -Path package\data -Destination "$Env:LOCALAPPDATA\Mulgyeol\Mulgyeol MK Bot" -Recurse
          cp -Path extensions -Destination $Env:USERPROFILE\.mkbot -Recurse
          cd .\build\app
          .\app.exe --dry-run
        shell: pwsh
      - name: Packaging
        run: |
          $Env:Path += ";C:\Program Files (x86)\NSIS\"
          makensis.exe /INPUTCHARSET UTF8 "/DPRODUCT_VERSION=${Env:mkbot_version}" "/DPRODUCT_NAME=Mulgyeol MK Bot" "/DPRODUCT_EXE=MKBot.exe" "/DEXT_DIR=.mkbot" package\MKBot.nsi
          mv package\MKBotSetup.exe .\
        shell: pwsh
