name: Nightly Build

on:
  schedule:
    - cron:  '0 15 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual Build'
        required: true
        default: 'true'

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check Latest Commit
    if: github.repository == 'mgylabs/mulgyeol-mkbot'
    outputs:
      is_new: ${{ steps.checkcommit.outputs.is_new }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Check Commit
      id: checkcommit
      run: |
        python package/ghtool.py -check
  canary-release:
    name: Nightly Build
    needs: check
    if: needs.check.outputs.is_new == 'true'
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      env:
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if (Test-Path Env:DEPLOY_TOKEN) { pip install -U mulgyeol-oauthlib --index-url https://${Env:DEPLOY_USER}:${Env:DEPLOY_TOKEN}@gitlab.com/api/v4/projects/20530638/packages/pypi/simple --extra-index-url https://pypi.org/simple }
      shell: pwsh
    - name: Version
      run: |
        python package/vc.py -gn
        echo "mkbot_version=$(cat version.txt)" >> $env:GITHUB_ENV
      shell: pwsh
    - name: Build MK Bot
      run: |
        call scripts\build.bat
    - name: Packaging
      run: |
        $Env:Path += ";C:\Program Files (x86)\NSIS\"
        makensis.exe /INPUTCHARSET UTF8 /DPRODUCT_VERSION=${Env:mkbot_version} package\MKBot.nsi
        mv package\MKBotSetup.exe .\
        Compress-Archive -Path MKBotSetup.exe -DestinationPath MKBotSetup.zip
      shell: pwsh
    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python package/ghtool.py -uca