name: Crowdin Upload

on:
  push:
    branches:
      - main
    paths:
      - "locales/mkbot.pot"

jobs:
  synchronize-with-crowdin-upload:
    if: github.repository == 'mgylabs/mkbot'
    runs-on: ubuntu-latest
    environment: Crowdin
    name: Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: crowdin action
        uses: crowdin/github-action@1.0.4
        with:
          upload_sources: true
          download_translations: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
